[package]
name = "timedelta"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.41.1", features = ["dtype-datetime", "lazy", "parquet", "regex", "strings", "temporal"], git = "https://github.com/pola-rs/polars" }
